apiVersion: v1
kind: Service
metadata:
  name: trend-service
  labels:
    app: trend
spec:
  type: LoadBalancer
  selector:
    app: trend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
